### ISSUE TITLE
Clear up tickets

### ISSUE THREAD

**Issue by Bilbo821** [ThroneCraft/public#101]
**Is your feature request related to a problem? Please describe.**
Make it so tickets automatically close when a player logs off so that way they can remake it when they log on otherwise we just have tickets sitting for days and weeks.

***Minecraft username:***
Bilbo821

**Comment by jvdoorn** [comment]
This is not supported in the current plugin. We'll see if there is a way that we can implement this.

**Comment by jvdoorn** [comment]
There are no good alternatives to this plugin. Our resolution is that tickets are handled as much as possible when a player is offline. If they have to be online for the ticket to be resolved then close it manually.
