### ISSUE TITLE
/C prayer not working

### ISSUE THREAD

**Issue by Zannythica** [ThroneCraft/public#102]
**Affected spells:**

/c prayer 
Prayer is from the priest pack. I asked one other player who has the spell who said it worked for them. Unfortunately it was not working for me. 

**Describe the bug**

So me and Finn the grand admin were deleting some of my spells and unfortunately after that prayer stopped working. He referenced me here. 

**Additional context**

I believe this can be resolved simply by just reteaching me the prayer spell/ giving me the prayer tome

***Minecraft username:***
zanithica

**Comment by Benlier** [comment]
Can confirm that zani should be able to cast the spell
![image](https://user-images.githubusercontent.com/16737998/100549221-f9e28f80-3271-11eb-9cb3-3f7e612c2ed0.png)

**Comment by Benlier** [comment]
@Zannythica what race are you playing as?

**Comment by Zannythica** [comment]
snowelf

**Comment by Benlier** [comment]
Successfully able to reproduce:
spell is casted and does nothing. No feedback
Repro: any race
