### ISSUE TITLE
Quality of Life: Colored Emotes with additional chat features

### ISSUE THREAD

**Issue by TheDragonsRoost** [ThroneCraft/public#105]
IGN: KytilSeren

I am writing another feature suggestion for the Thronecraft server and this time, it is for the chat plugin. Most roleplay servers allow Minecraft color codes and (since 1.16) hex colors. I want to see the chat plugin update to where players can color their emotes and even use bold, italics, and potentially strikethrough in their roleplay to further empathize the quality of roleplay.

For instance, instead of players doing /this/ to empathize italics, it would appear as _this_.

To also add further chat improvements or features, there could also be a feature to allow a continuation of an emote by adding a symbol that is configured in the player's settings such as -, +, or >.

_I am also writing this while incredibly exhausted so, please forgive me if this seems short._

**Comment by Brsssh** [comment]
Hmm... I don't imagine colors would be added but I don't think bold italic and strikethrough wouldn't be terrible to add with the current plugin... maybe +This would be Bold+ -This would be striked- \This would be italic\ (It would have to be that slash so it wouldn't think you're trying to do a command)

**Comment by TheDragonsRoost** [comment]
I disagree because the plugin that is on TC currently allows players to have yellow emotes and I do think that it can be possible to add some code to alter this setting so that in the server, playera can have different colors based on the minecraft color codes or the hex codes once updated to 1.16 and beyond.

Other than that, I agree with your assessment on the bold, italic, and strikethrough. Obviously there are more formats that can alter the letters of a word, but I just think that we can also add underline to this as well (my idea is to use the % symbol for this)

**Comment by Brsssh** [comment]
I'm not saying it wouldn't be possible to add other colors, I'm saying it's unlikely it would be added because there's already the color system in place

**Comment by TheDragonsRoost** [comment]
A color system for the emotes already in place? If this is true then why have I not heard about this?

**Comment by jvdoorn** [comment]
Color codes are automatically applied to emotes (yellow). Same goes for OOC text (gray).

**Comment by TheDragonsRoost** [comment]
> Color codes are automatically applied to emotes (yellow). Same goes for OOC text (gray).

That is the problem that I am addressing in terms of the emote coloration. OOC can remain as it is, but I was asking for the ability to change these colors to add various cosmetic changes. I feel like just having the yellow for emotes does not give enough diverse changes.

Perhaps a player wants to have an aqua color or another wants to have a red color? They cant change the color if is hardwired to stay yellow the entire time.

**Comment by jvdoorn** [comment]
I do not see how that would improve the user experience. It will only add an extra layer of inconsistency where colours do not automatically indicate the intent of a message (spoken, emote, etc.). I do see the use of italic (preferred over bold) formatting to indicate an accent in spoken text. Par example `"We /must/ do this!"` -> "We *must* do this!".

**Comment by TheDragonsRoost** [comment]
The reason why I am suggesting colored emotes is for cosmetic change. The extra formatting (bold, italics, etc) is useful for immersive experience.

Im not trying to suggest that the entire color system be changed to accommodate for colored emotes, but there could be a possible setting for this.

Also, would anyone disagree to adding the ability to make emotes more detailed through the use of symbols at the end of the emote like > or =?
