### ISSUE TITLE
My frown is turned upside down  !!

### ISSUE THREAD

**Issue by Cake1100** [ThroneCraft/public#107]
Here is a video which shows all...

https://streamable.com/97jiu1

ps: my discord isnt linked to ingame

**Comment by Benlier** [comment]
We did it @jvdoorn! We fixed sadness and made everyone happy!

**Comment by Benlier** [comment]
You can type ((:( for a frown

**Comment by jvdoorn** [comment]
Starting your message with `((` will turn the whole message OOC. The chat plugin will then not touch any formatting. You can use that to get your smileys.
