### ISSUE TITLE
(In-Game) Staff Chat

### ISSUE THREAD

**Issue by Bilbo821** [ThroneCraft/public#109]
***What is the feature & it's purpose?:***
An in-game staff chat! Similar to global whisper etc, a chat for online staff members to easily communicate in-game for cases where we want to be able to talk to more than one member outside of /msg or quicker than switching to discord since sometimes we may be in RP and its quicker to see in-game chat messages.

***Feature Detail:***
The command would be simply where its like /staffchat or if possible /sc for shortand you type your message. Who should be able to see the chat? GA, Admin, Mod, JrMod.

&3[SC] <IGN>:  [message sent here]

***Minecraft username:***
IndeanaJones

**Comment by instrumentalityi** [comment]
Simple version produced, awaiting revision by operator
