### ISSUE TITLE
Mending fishing rate suddenly much lower?

### ISSUE THREAD

**Issue by LouiseLArt** [ThroneCraft/public#111]
**Describe the bug**

After the server was updated to the latest version of minecraft I had no problems fishing mending with my high tier fishing rod. About a week ago I've noticed mending books seem to have become impossible to fish? I usually was able to fish about 3 a day but after 4 irl days of fishing, nothing. Someone suggested it might be due to all the new enchants that we can now fish. This might be the case but the rate at witch we can fish mending becoming so drastically low is a problem.

**Additional context**

This problem mostly effects people, such as myself, who's only or central income source is the sale of mending books. This of course means the prices can be doubled, if not more, but sadly most people wouldn't even consider buying a mending book at lets say 2 stacks.  

***Minecraft username:***

LouiseLArt

**Comment by jvdoorn** [comment]
Have the amounts of enchantment books changed? Or are you still getting the same amount (roughly)?

**Comment by LouiseLArt** [comment]
The amounts don't seem to have changed so I'm guessing it might be the new enchants making the likelihood of fishing mending lower? Even though it didn't start right after the update.

**Comment by LouiseLArt** [comment]
> Have the amounts of enchantment books changed? Or are you still getting the same amount (roughly)?

**Comment by LouiseLArt** [comment]
Sorry, must have accidentally closed it.

**Comment by jvdoorn** [comment]
I honestly think you might have just been having bad luck. There is a chance that you get an enchanted book (which as you say hasn't changed) but of for those books there is again a chance that you get mending (or not). We checked with the staff team and no-one has changed any configurations. We'll be closing this issue for now.
