### ISSUE TITLE
Player data reset on restart

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/public#113]
**Describe the bug**

So, this bug has been going on for as long as I can remember but I just got so used to it I didn't even think of reporting it until just now because we've had to live with it so long. Sometimes changes made to a persons character card are reset at the daily server reset. For example, if I had +1 added to one of my stats at any point during the day, there's a chance I might lost that at the reset and need to have it added by staff again. Or if I at some point set my nickname to 'Ben wearing a Julian mask' for a short period of time, before resetting it back to normal, after the reset there's a chance it may revert my name back to 'Ben wearing a Julian mask'. The bug isn't consistent, sometimes it messes the things up, sometimes it doesn't. I assume it would have something to do with how that information is saved to the server and could be solved by either saving more frequently or having it all saved just before reset. 

**Additional context**

It isn't a horribly large issue, if it resets your name you can just set it with one command, if it resets your stats you can just get a staff member to fix them, but it is kindof annoying and would be nice if it could be fixed.

***Minecraft username:***

Brsssh

**Comment by jvdoorn** [comment]
Good catch!
