### ISSUE TITLE
World Edit

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/public#117]
**Describe the bug**

A clear and concise description of what the bug is. When did you first experience this problem? And how to reproduce it? What did you expect to happen?

**Screenshots**

![571897AB-37CF-4872-BE98-DBFA833CE3B5](https://user-images.githubusercontent.com/72952343/102701421-b2be3d80-4224-11eb-989c-aea5f8cd916e.jpeg)
![43A570E7-F14A-49B7-A83A-126596EB1C68](https://user-images.githubusercontent.com/72952343/102701422-b356d400-4224-11eb-802d-492d6c4c7191.jpeg).

***Minecraft username:***

Brsssh

**Comment by jvdoorn** [comment]
The `//flip` command appears to work fine, just note that numbers are not supported instead use one of the suggested values. We've been unable to reproduce the issue of Keitara, if this persists please create a dedicated issue for it.
