### ISSUE TITLE
/walk

### ISSUE THREAD

**Issue by Bewby** [ThroneCraft/public#119]
**Is your feature request related to a problem? Please describe.**
Yes, sometimes walking fast ruins vibes.

**Describe the solution you'd like**
A /walk command, to go slower.

**Describe alternatives you've considered**
If /walk doesn't work, then allow /speed but only numbers 1 and below so people can slow down but not speed up.

**Additional context**
None

***Minecraft username:***
Bew

**Comment by jvdoorn** [comment]
We do not see a big use-case for this, nor that it is applicable to many races other than elves. Perhaps in the future.
