### ISSUE TITLE
A lesser currency

### ISSUE THREAD

**Issue by Bewby** [ThroneCraft/public#120]
**Is your feature request related to a problem? Please describe.**
It's annoying that once coin buys a whole stack of food. All drink prices are basically scams because they can't possible lower the price without giving people multiple drinks. 

**Describe the solution you'd like**
Some item like crowns created to be 1/9th of a crown. And allow it to be crafted so that 9 of these lesser coins in the crafting table make 1 crown. It would have to default to the special names, and any coin with the special names have to have the normal recipe if the recipe is already used by default stuff.

**Describe alternatives you've considered**
Alternatives are to completely remove crowns and start a new money system but that involves more than just some dev work.

**Additional context**
None

***Minecraft username:***
Bew

**Comment by jvdoorn** [comment]
The staff has the ability to create other currencies. It is up to them to manage this.
