### ISSUE TITLE
Drink flavor descriptions

### ISSUE THREAD

**Issue by Bewby** [ThroneCraft/public#121]
**Is your feature request related to a problem? Please describe.**
A lot of drinks exists and players tend to decide for themselves how things taste, it would be better if it was consistent.

**Describe the solution you'd like**
Add a flavor description to all drinks, if possible. not idea if it's possible.

***Minecraft username:***
Bew

**Comment by jvdoorn** [comment]
Sadly it is not possible to do so with the plugin we currently use (Brewery).
