### ISSUE TITLE
WE Issue //move

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/public#123]
**Describe the bug**

When attempting ‘//move 2 down’ on a build, which should have moved the entire selection 2 blocks downward, instead only the bottom two layers of the build were moved downward, the rest was cleared. 

**Additional context**

The proper usage of this command is //move (number of directional blocks to move, if left blank automatically set to 1) (direction (north/south/east/west/up/down) if left blank set to the direction the player is facing)

example: //move 2 east moves an entire selection 2 blocks east. //move moves an entire selection 1 block whichever way the user is facing

***Minecraft username:***

Brsssh

**Comment by Brsssh** [comment]
This can be seen at time stamp 1:02:00 in this stream, where I saw what it did, then undid it shortly after https://www.twitch.tv/videos/848848169

**Comment by jvdoorn** [comment]
I've been unable to reproduce this issue. It is possible that it was patched during an update. Could you please try again?
