### ISSUE TITLE
Coin Purses

### ISSUE THREAD

**Issue by Bilbo821** [ThroneCraft/public#124]
**Is your feature request related to a problem? Please describe.**
Creating a coin purse (function similar to key ring and acts as a shulker for crowns)

**Describe the solution you'd like**
https://thronecraft-server.enjin.com/forum/m/13784224/viewthread/33376575-plugin-idea

***Minecraft username:***
IndeanaJones

**Comment by jvdoorn** [comment]
There are some other features we are currently working on that will solve this issue. Please await those!
