### ISSUE TITLE
WE very slow

### ISSUE THREAD

**Issue by Bewby** [ThroneCraft/public#127]
**Describe the bug**

World edit is very slow sometimes. That command I ran finally completed after about 5 minutes. The city will take weeks longer to complete if this continues. Other builders have the issue too, they have been complaining about it since day one of switching to this version of world edit.

**Screenshots**

https://www.twitch.tv/bewberries/clip/GiftedTrappedPlumberHeyGuys

***Minecraft username:***

Bew

**Comment by jvdoorn** [comment]
This is certainly not intended. We will see about increasing the speed of operations.

**Comment by jvdoorn** [comment]
We've made some changes, performance should be better. If this is not the case please let us know. If we do not receive a response in the next few days we will assume that this issue is resolved.

**Comment by jvdoorn** [comment]
I'll assume it is solved!
