### ISSUE TITLE
Automated Item gathering system

### ISSUE THREAD

**Issue by Bilbo821** [ThroneCraft/public#64]
**Is your feature request related to a problem? Please describe.**
Suggestion from Keitara found here: https://thronecraft-server.enjin.com/forum/m/13784224/viewthread/33290648-automated-item-gathering 

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

***Minecraft username:***
Bilbo821

**Comment by Benlier** [comment]
@Bilbo821 This sounds awesome, and I would love to implement something like this.
However adding this will have an impact on the in-game market, depending on how many resources players can get from this. I'll have to ask my manager @jvdoorn about this.
