### ISSUE TITLE
Include bows in /roll rs

### ISSUE THREAD

**Issue by Benlier** [ThroneCraft/public#65]
**Is your feature request related to a problem? Please describe.**
Making combat rolls when using a bow could be a lot easier than it is now

**Describe the solution you'd like**
the ranged damage rolls have been needing a fix for a long time for one; could those be fixed to register as rolling 1d6 if a bow is in hand? i know swords go off the formula of (type)+(sharpness up to 2)+S- bows go off of (1d1 increased by the power level up to 1d6) i think
and might there be a way to tack on a query for Fire Aspect/Flame enchants? just so those might be automated as well

**Describe alternatives you've considered**
Crying a lot

**Additional context**
This was suggested by Keitara

***Minecraft username:***
Bencoder

**Comment by jvdoorn** [comment]
So to be clear, rolling `RS` you roll a max of six. If you are holding a bow and that bow has the power enchantment add the level of that enchantment to the roll (with a maximum of 6). 

What do you need to be changed regarding fire aspect/flame?

**Comment by Benlier** [comment]
Hold up, it gets more complicated. Not all bows are bows, they can also be crossbows because for some reason we're not using crossbows (the item) on the server yet. Crossbows' rolls are calculated differently

**Comment by jvdoorn** [comment]
Is there perhaps a forum post explaining these mechanics?

**Comment by Brsssh** [comment]
https://thronecraft-server.enjin.com/forum/m/13784224/viewthread/32431784-expansion-range-skill

**Comment by Benlier** [comment]
The /roll damage command already takes the power of a held bow into account.
Fire aspect should not be added in the roll because it is a different 'damage type' that targets might have modifiers against (flamewalker armor, fire resist potion, being under water). Mixing these damage types would complicate the system as much as this solution is trying to solve
