### ISSUE TITLE
An Event Chat

### ISSUE THREAD

**Issue by Bilbo821** [ThroneCraft/public#68]
**Is your feature request related to a problem? Please describe.**
When running an event interaction with a large crowd it can be hard  to really follow who's in charge and what they are saying and can lead to people losing out on important event information.

**Describe the solution you'd like**
Similar to /w or /s I would like a chat made for Event that appears to everyone like RP chat. So when someone speaks in this chat it appears as [Event] (I propose a bold light  green (&a) maybe so it stands out. Give it the same range as RP chat maybe a little more between RP range and shout range.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

***Minecraft username:***
Bilbo821

**Comment by Benlier** [comment]
@Bilbo821 How does this look?
![image](https://user-images.githubusercontent.com/16737998/98865748-29b92700-246c-11eb-9fa3-1aabb0ebcbe6.png)

**Comment by Benlier** [comment]
I feel like the bold text looks odd in conquest. Almost like I'm drunk

**Comment by jvdoorn** [comment]
Perhaps italics is a better choice?

**Comment by Benlier** [comment]
@jvdoorn 
![image](https://user-images.githubusercontent.com/16737998/98867761-6b979c80-246f-11eb-9e8f-ca3e6f4039c5.png)

**Comment by jvdoorn** [comment]
It stands out and is quite readable. I would suggest not putting the tag in italics though.

**Comment by Benlier** [comment]
Just wanted to throw this into the mix also
![image](https://user-images.githubusercontent.com/16737998/98868620-b82fa780-2470-11eb-80b3-19c0c192052e.png)

**Comment by Benlier** [comment]
I prefer the underlined one

**Comment by jvdoorn** [comment]
I honestly find it a bit intrusive and unnatural looking.

**Comment by Brsssh** [comment]
Maybe make it /ec or something simple so they don't have to type out eventchat for every emote
That or make a command to lock your default chat to one channel, though still able to type in other channels, like:

/chat s or /chat shout then locks you in shout, but by doing /rp "message" it says message in rp chat, but keeps the default chat in whatever you have locked in

**Comment by Benlier** [comment]
> Maybe make it /ec or something simple so they don't have to type out eventchat for every emote
> That or make a command to lock your default chat to one channel, though still able to type in other channels, like:

I was thinking about that yeah, but /ec is /enderchest. /eventc was the best I could come up with
 
> /chat s or /chat shout then locks you in shout, but by doing /rp "message" it says message in rp chat, but keeps the default chat in whatever you have locked in

Hell no, that's a separate issue

**Comment by Benlier** [comment]
Going by the poll it seems it'll be italic. @Bilbo821 also asked me to put the Event tag in bold. Does this please you?
![image](https://user-images.githubusercontent.com/16737998/98872790-75bd9900-2477-11eb-8087-8914c6941285.png)

**Comment by jvdoorn** [comment]
I'd prefer to not to make the tag bold. It's more consistent with the other channels.

**Comment by Benlier** [comment]
Yeah it almost looks like it's trying to spell "Ewemt"
