### ISSUE TITLE
Armorstand Furniture Plugin

### ISSUE THREAD

**Issue by Bewby** [ThroneCraft/public#69]
I suggest this plugin. It will provide more creative decorational things that help the server stand out above a normal rp server. I have not looked into it much, I just know I've always wanted to use stuff like this in my builds.

https://www.spigotmc.org/resources/dicefurniture-plugin-m%C3%B6bel-plugin.6006/

It does have another plugin dependency too btw.

- Bew

**Comment by Benlier** [comment]
@Bewby Do you see this as something to be used by builders, or all players?
