### ISSUE TITLE
A year command

### ISSUE THREAD

**Issue by Bilbo821** [ThroneCraft/public#70]
**Is your feature request related to a problem? Please describe.**
A command for when you do /year it tells you the RP year that is automated increasing every month.

**Describe the solution you'd like**
A /year command in which it displays the date, and increases every month. For example this month of (November) would be 586 HE, next month during (December) it would be 587 and so on. 

**Describe alternatives you've considered**
N/A

**Additional context**

Format - 
Year (aqua blue &3): (insert year here in white color) 

***Minecraft username:***
Bilbo821

**Comment by Benlier** [comment]
@Bilbo821 Are years actually canon to be taken into RP when it happens? I only see it being used to refer to past events

**Comment by Brsssh** [comment]
The year currently is used irp the issue is that no one ever actually knows what the current year is aside from a few people

**Comment by Bilbo821** [comment]
Yep they are canon in RP. The current timeline we have uses this year system where there are historic months tracked during that month. So this sort of command would be helpful so people aren't always asking for the year and can just check.
