### ISSUE TITLE
chat toggle

### ISSUE THREAD

**Issue by Emamou** [ThroneCraft/public#74]
**Is your feature request related to a problem? Please describe.**
Accidentally typing /g instead of /r in chat when responding to a private message, resulting in the message appearing in global chat for everyone to see.  

**Describe the solution you'd like**
A way to toggle global chat completely so that even if you accidentally type /g instead of /r, the message will not be broadcasted to global chat.

***Minecraft username:***
Emamou

**Comment by Benlier** [comment]
Suggested flow:
User uses command /chat [rp, s, g, r, w]. No parameter displays current chat channel and command usage
On playerChatEvent: handle corresponding channel
Default channel is RP
Reset channel to RP on login

**Comment by jvdoorn** [comment]
I can see that implemented for event, rp, shout, whisper and global. Not sure about private messages though. We could add a check to global that requires you to manually toggle it before sending messages.

**Comment by Emamou** [comment]
> I can see that implemented for event, rp, shout, whisper and global. Not sure about private messages though. We could add a check to global that requires you to manually toggle it before sending messages.

Would that mean that you wouldn't see global chat anymore whilst replying to private messages? Or would it only prevent you from accidentally sending your PM to global? As currently, our /toggle hides global chat from view.

-----

> Suggested flow:
> User uses command /chat [rp, s, g, r, w]. No parameter displays current chat channel and command usage
> On playerChatEvent: handle corresponding channel
> Default channel is RP
> Reset channel to RP on login

Just to recap to make sure I understood correctly, what is being suggested is using /chat [rp, s, g, r, w] as a way to "enter" a chat.
So if you type in /chat g, for example, you enter global chat, meaning every message you type in from now on will appear in global chat. If you then wish to switch back to IC, you would do /chat rp. If you wish to shout, you would do /chat s, and so on and so forth.

Private messages could still be via the command /r, because since you're no longer using /g to talk in global, your message shouldn't accidentally be sent to global chat. Even if you're currently in /chat g, (unless you respond to the PM without typing /r before your reply), it won't be sent to global chat, so that fixes the issue.

**Comment by Benlier** [comment]
@jvdoorn When you say you don't see pm's implement, are you unsure of how it would work programatically?

**Comment by jvdoorn** [comment]
I meant that to me it does not make sense to implement it for pms.

**Comment by Benlier** [comment]
> Just to recap to make sure I understood correctly, what is being suggested is using /chat [rp, s, g, r, w] as a way to "enter" a chat.
> So if you type in /chat g, for example, you enter global chat, meaning every message you type in from now on will appear in global chat. If you then wish to switch back to IC, you would do /chat rp. If you wish to shout, you would do /chat s, and so on and so forth.

Yes, but be mindful that the original commands (/g /s /w) are still available.

> Private messages could still be via the command /r, because since you're no longer using /g to talk in global, your message shouldn't accidentally be sent to global chat. Even if you're currently in /chat g, (unless you respond to the PM without typing /r before your reply), it won't be sent to global chat, so that fixes the issue.

Perhaps private message chats would be better used if instead of using `/chat r` we use `/chat msg [playername]`
This prevents you from accidentaly responding to the wrong person

**Comment by Benlier** [comment]
> I meant that to me it does not make sense to implement it for pms.

The current issue is accidentally typing /g instead of /r in chat when responding to a private message.
Unless we want to change /g or /r, it would be best to provide a new way of responding to PMs

**Comment by jvdoorn** [comment]
After a team meeting, it has been decided that implementing a `/chat [channel]` command will not improve the user experience. The issue will remain that people will forget to enter the command before sending a message. We have considered changing the command names but after a poll, it was clear that people did not want that.

As such it has been decided to close this feature request.
