### ISSUE TITLE
Teamspeak isn't real, Teamspeak can't hurt you

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/public#76]
**Describe the bug**

The server no longer has a teamspeak server but thronecore still announces to use it

**Screenshots**

![0 0000000000000000000000000000000000000](https://user-images.githubusercontent.com/72952343/99138211-aecf4800-25f4-11eb-9eec-f8d8c481301f.png)

***Minecraft username:***

Brsssh

**Comment by jvdoorn** [comment]
The TeamSpeak is very much real!
