### ISSUE TITLE
Chest Locking Bug

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/public#77]
**Describe the bug**

When locking double chests, instead of also locking the chest connected to the chest you lock, the plugin locks the chest on the other side. The key for the initially locked chest still works for the unintentionally locked chest, but you can still access the inventory of the chest thats supposed to be locked by opening its other half which remains unlocked. Screenshots of my tests are included showing how the bug works.

**Screenshots**

![ChestsBug1](https://user-images.githubusercontent.com/72952343/99154842-8426d300-2678-11eb-891e-953cdffb382f.jpg)
![ChestBug2](https://user-images.githubusercontent.com/72952343/99154846-85f09680-2678-11eb-8c74-90cfe56d0526.jpg)

***Minecraft username:***

Brsssh

**Comment by oxXHeartlessXxo** [comment]
_Date: 11/15/2020_

After removing the chests to have two blocks in-between them, I found out that not only does it lock the chest, a block away. It locks the entire block next to it. I was texturing the wall when I discovered this.

_Discord: oxXHeartlessXxo#4158_
