### ISSUE TITLE
Edged Leggings Repair Bug

### ISSUE THREAD

**Issue by DiamondTanner** [ThroneCraft/public#78]
When I attempt to repair my Edged (chain) Leggings with anything (I usually use Iron as its cheaper), it will repair, but when I exit the anvil menu, the edged aren't repaired, I have the same amount of Iron as I started with, and I have lost the levels.

![2020-11-14_15 26 58](https://user-images.githubusercontent.com/74472464/99157449-767c4800-268e-11eb-860b-2b3295e0eccc.png)

![2020-11-14_15 28 00](https://user-images.githubusercontent.com/74472464/99157451-7a0fcf00-268e-11eb-8b08-4fa946e944f7.png)

![2020-11-14_15 28 22](https://user-images.githubusercontent.com/74472464/99157454-8005b000-268e-11eb-93f4-98034f461854.png)

DiamondTanner

**Comment by Benlier** [comment]
Unable to reproduce on the test server
@jvdoorn perhaps test it on the main server?

Damaged edged leggings repair as intended
![image](https://user-images.githubusercontent.com/16737998/99157947-c6c6ca80-26cd-11eb-8f52-dc538bad14d0.png)
![image](https://user-images.githubusercontent.com/16737998/99157954-d7774080-26cd-11eb-9e10-dc56dc94ff24.png)

luckperms verbose logging of repair
![image](https://user-images.githubusercontent.com/16737998/99157977-08577580-26ce-11eb-8ae1-c3a76f932f0d.png)

Tester info:
![image](https://user-images.githubusercontent.com/16737998/99157994-389f1400-26ce-11eb-942f-197752149a04.png)
![image](https://user-images.githubusercontent.com/16737998/99157997-42287c00-26ce-11eb-8785-73bfdd2380a5.png)

**Comment by Benlier** [comment]
With the help of @DiamondTanner I was able to reproduce the issue on the main server @ -1328/57/-4701/thronecraftchapter3 using my bencoder profile.
Repairing other items works just fine

**Comment by jvdoorn** [comment]
Does it maybe have to do with the length of the lore?

**Comment by Benlier** [comment]
Probably not, because then I wouldn't have been able to repair them without issues on the test server

**Comment by Brsssh** [comment]
I was also unable to repair my arcanist gear this way

**Comment by jvdoorn** [comment]
We tested it today and were unable to reproduce the issue. We suspect it might have been a temporary thing. If the issue persists please reopen this issue.
