### ISSUE TITLE
Dono keys not automated

### ISSUE THREAD

**Issue by loulou71192** [ThroneCraft/public#81]
**Describe the bug**

We've had a problem with several players purchasing dono keys whilst online on the server but they have not been placed into their inventory as expected.

**Additional context**

These have now been given by staff but if this could be looked at ASAP it would be appreciated as it should be working.

***Minecraft username:***

loulou71192

**Comment by Benlier** [comment]
Since when has this been the case @loulou71192? Did it start recently or has it been going on for a while

**Comment by jvdoorn** [comment]
I have just tested it and donated for 20 keys. That worked fine. A common pitfall is that people enter the wrong name. Could you confirm this is not the case?

**Comment by loulou71192** [comment]
First noticed it yesterday but unsure when someone last bought keys prior.
I know there was an issue with a dono key not working the day before too.

**Comment by loulou71192** [comment]
Yeah, just realised that it was two that had recently changed their usernames and presumably hadn't changed on the website! Thanks guys!

**Comment by jvdoorn** [comment]
Alright, that solves it!
