### ISSUE TITLE
Character Profile Plugin (Similar to LotC)

### ISSUE THREAD

**Issue by TheDragonsRoost** [ThroneCraft/public#82]
***Minecraft username:***
KytilSeren

I am writing a suggestion for ThroneCraft to create a plugin similar to LotC's plugin to switch character profiles which would allow players to quickly go to another character with their relevant inventories. I'd think it'd be a good Quality of Life plugin to help the players switch characters without having to interrupt other character's progress.

**Comment by Brsssh** [comment]
It's unclear exactly what you're requesting for this, whether you mean a way to save your character's stats and such then be able to switch between characters when the time comes with a simple command, or an alteration on the shelving rules so you can play multiple characters at once. If it is the second scenario, I would advise you make a suggestion for a change to the shelving rules here: https://thronecraft-server.enjin.com/forum/m/13784224/viewforum/6831558 though I believe the current stance of the Thronecraft Staff team is that having multiple characters playable at once would result in people creating characters to benefit other characters of theirs

**Comment by TheDragonsRoost** [comment]
I'm requesting a plugin that allows you to save your character's stats, inventory, etc and switch between characters through a command and gui prompt.

**Comment by jvdoorn** [comment]
Well we get that. However there is no case where people switch characters often so we don't get the point of it.

**Comment by jvdoorn** [comment]
So maybe you can elaborate on the use case?

**Comment by TheDragonsRoost** [comment]
It would allow players with multiple characters (I personally dont know who does do multiple characters often, but I do on other servers) to do a command (maybe /switch or /char gui) that would open up an inventory GUI that would show the slots available for characters. Clicking on the player head (or wither skull) would allow the player to change to that character at their last known location with their entire inventory-armor and all.

This would also load up their character card and relevant stats, applying them every time they'd change. If they also shelve a character, they could make a ticket to get someone on staff to unlock the character so that they can rotate that character back in.

**Comment by Brsssh** [comment]
It /might/ be useful for simplicity sake if a cooldown were put on it so you could only switch once a month that way you won't need staff involvement to switch characters... I'm not sure that would be worth the coding of writing up a whole plugin though

**Comment by jvdoorn** [comment]
We don't see widespread use for this. This can be reopened if mechanics change in the future which makes this more widely applicable.
