### ISSUE TITLE
Mute command

### ISSUE THREAD

**Issue by Bilbo821** [ThroneCraft/public#83]
**Is your feature request related to a problem? Please describe.**
/mute command prevents someone from talking in rp chat rather than global

**Describe the solution you'd like**
Fix /mute so it prevents people from talking in global but not RP chat.

**Describe alternatives you've considered**
N/A

**Additional context**
Also give admins the /mute command.

***Minecraft username:***
Bilbo821

**Comment by jvdoorn** [comment]
It appears that Essentials does not allow chat in any way when someone is muted. We'll internally discuss how we can tackle this issue.

**Comment by jvdoorn** [comment]
Might integrate nicely with #108 so that a user also gets muted in the Discord.
