### ISSUE TITLE
Using /roll [random number] always results in rolling d20

### ISSUE THREAD

**Issue by Soelaire** [ThroneCraft/public#88]
**Describe the bug**
When you type /roll [insert number here], it always results in rolling d20 rather than custom dx. There are various situations that require custom dx (fine examples are spell damage, mesmerize bourgia clan trait, DC, etc.).

**Screenshots**
![2020-11-24_06 40 46](https://user-images.githubusercontent.com/70114241/100109355-99da8c00-2e20-11eb-8ab3-1b61b73daa70.png)

***Minecraft username:*** SoelaireCS
Forums/Discord Username: Soelaire

**Comment by jvdoorn** [comment]
Same goes for rolling for a stat without modifiers (such as `/roll RS`).
