### ISSUE TITLE
Missing Colour

### ISSUE THREAD

**Issue by Azilerle** [ThroneCraft/public#93]
**Describe the bug**

Once linking the discord bot to my account, my helper colour in tab disappeared and turned into the city tag.

**Screenshots**

https://media.discordapp.net/attachments/751979800146477077/781278108342288464/unknown.png

***Minecraft username:***
Aziee

**Comment by jvdoorn** [comment]
We were unable to reproduce this issue today. Please reopen this issue if problems persist.
