### ISSUE TITLE
Boss bug

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/public#99]
**Describe the bug**

I was boss hunting with a group and as we went to the spider boss we saw something strange. It was already spawned in (shouldn't happen, it should have to be spawned in by a staff member) we killed it without really thinking about it, as it attacked us and we kindof had to, but when it died it dropped nothing (another error as it should drop a bunch of stuff based on the loot table)

**Additional context**

Not sure what specifically the issue here would be, I think if another group had died to it then it should have despawned and even then it still should have dropped loot. I have no idea why it would do this

***Minecraft username:***

Brsssh

**Comment by Brsssh** [comment]
Update, upon having the boss spawned in, it either despawned, or was killed with one hit and dropped nothing

**Comment by FInnJp** [comment]
Seems like when I recently updated the world guard to include pillagers (and drowned again), I had used the same updated one on the spider location, which did include spiders being denied to spawn. This I believe caused a faulty spider boss to spawn (as it wasnt supposed to be able to spawn in the first place it seems). Anyhow, that should be fixed now.
